apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaterbrain-musicstore
  labels:
    app: scaterbrain-musicstore
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: scaterbrain-musicstore
  template:
    metadata:
      labels:
        app: scaterbrain-musicstore
    spec:
      containers:
      - name: musicstore
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"